export const COMMANDS = [
  { command: '/payments list', description: 'List your payments' },
  { command: '/payments info', description: 'Get payment detail' },
  { command: '/products list', description: 'List your products' },
  { command: '/products create', description: 'Create a product (opens browser)' },
  { command: '/products info', description: 'Get product detail' },
  { command: '/customers list', description: 'List your customers' },
  { command: '/customers create', description: 'Create a customer' },
  { command: '/customers update', description: 'Update a customer' },
  { command: '/customers portal', description: 'Create a temporary customer portal session' },
  { command: '/discounts list', description: 'List your discounts' },
  { command: '/discounts create', description: 'Create a discount' },
  { command: '/discounts delete', description: 'Delete a discount' },
  { command: '/licences list', description: 'List licence keys' },
  { command: '/addons list', description: 'List addons' },
  { command: '/addons create', description: 'Create an addon (opens browser)' },
  { command: '/addons info', description: 'Get addon detail' },
  { command: '/refunds list', description: 'List refunds' },
  { command: '/refunds info', description: 'Get refund detail' },
  { command: '/wh listen', description: 'Listen to live webhook events' },
  { command: '/wh trigger', description: 'Trigger a webhook event offline' },
  { command: '/checkout new', description: 'Create a checkout session' },
  { command: '/ai', description: 'Ask a question about your data' },
  { command: '/login', description: 'Login with a Dodo API key' },
  { command: '/init nextjs', description: 'Next.js App Router billing routes' },
  { command: '/init express', description: 'Express server billing routes' },
  { command: '/init better-auth', description: 'Better-Auth plugin configuration' },
  { command: '/logout', description: 'Logout from stored accounts' },
  { command: '/switch', description: 'Switch between Test and Live modes' },
  { command: '/update', description: 'Update the CLI to the latest version' },
  { command: '/clear', description: 'Clear message history' },
  { command: '/exit', description: 'Exit the CLI' },
  { command: '/help', description: 'Show all commands' },
];