name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below to help us understand and fix the issue.

  - type: checkboxes
    id: existing-issue
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true

  - type: dropdown
    id: command
    attributes:
      label: CLI Command
      description: Which command is affected?
      options:
        - dodo login
        - dodo products
        - dodo payments
        - dodo customers
        - dodo discounts
        - dodo licences
        - dodo wh (webhooks)
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run 'dodo ...'
        2. Select '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Please copy and paste any relevant error messages or logs. This will be automatically formatted into code.
      render: shell

  - type: input
    id: version
    attributes:
      label: CLI Version
      description: What version of the CLI are you running? (Check package.json or npm list -g dodopayments-cli)
      placeholder: e.g., 0.1.0
    validations:
      required: true

  - type: input
    id: runtime
    attributes:
      label: Runtime & Version
      description: Are you using Bun or Node? What version? (Run `bun --version` or `node --version`)
      placeholder: e.g., Bun 1.1.0 or Node 20.10.0
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Windows
        - Linux
        - Other
    validations:
      required: true

  - type: dropdown
    id: mode
    attributes:
      label: Environment Mode
      description: Were you using test mode or live mode?
      options:
        - Test Mode
        - Live Mode
        - Not applicable

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
